name: Release

on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - run: yarn --frozen-lockfile
    - run: yarn test

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - run: yarn --frozen-lockfile --production
    - uses: fregante/setup-git-user@v1
    - run: yarn release
    - name: publish-npm
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.npm_token}}
